export default {
  ACCESS_KEY: '',
  SECRET_KEY: '',
  TELEGRAM_BOT_TOKEN: '',
  TELEGRAM_CHAT_TOKEN: '',
  MARKET: 'KRW-BTC',
  K: 0.5,
  CRYPTO_SYMBOL: 'BTC',
  HIGH_TRIGGER_RATE: 1.14,
  LOW_TRIGGER_RATE: 0.98,
}
