import { MAX } from 'uuid'

export default {
  ACCESS_KEY: '',
  SECRET_KEY: '',
  TELEGRAM_BOT_TOKEN: '',
  TELEGRAM_CHAT_TOKEN: '',
  MARKET: 'KRW-BTC',
  CRYPTO_SYMBOL: 'BTC',
  HIGH_TRIGGER_RATE: 1.14,
  LOW_TRIGGER_RATE: 0.98,
  SWAP: {
    RPC: '',
    PRIVATE_KEY: '',
    MIN: 0.985,
    MAX: 1.015,
  },
  INVESTMENT_LIST: [
    {
      MARKET: 'KRW-BTC',
      CRYPTO_SYMBOL: 'BTC',
      MINUMUM_SELL_AMOUNT: 0.0005,
      MIMUMUM_TRANSACTION_UNIT: 1000,
      HIGH_TRIGGER_RATE: 1.14,
      LOW_TRIGGER_RATE: 0.98,
      INVESTMENT_RATIO: 0.7,
    },
    {
      MARKET: 'KRW-SOL',
      CRYPTO_SYMBOL: 'SOL',
      MINUMUM_SELL_AMOUNT: 0.1,
      MIMUMUM_TRANSACTION_UNIT: 100,
      HIGH_TRIGGER_RATE: 1.14,
      LOW_TRIGGER_RATE: 0.98,
      INVESTMENT_RATIO: 0.3,
    },
  ],
}
